services:
  influxdb:
    container_name: k6-influxdb
    image: influxdb:1.8-alpine
    environment:
      INFLUXDB_DB: k6
    ports:
      - "8086:8086"
    volumes:
      - k6_influxdb_data:/var/lib/influxdb

  grafana:
    container_name: k6-grafana
    image: grafana/grafana:latest
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    ports:
      - "3001:3000"
    volumes:
      - k6_grafana_data:/var/lib/grafana
      - ./apps/api-core/test/k6/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb

volumes:
  k6_influxdb_data:
  k6_grafana_data:
